
# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: #19181d;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 320, 71))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 60pt;\n"
"    color:  #FFF;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_play = QtWidgets.QPushButton(Dialog)
        self.btn_play.setGeometry(QtCore.QRect(165, 130, 70, 70))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border-radius: 35px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #28272c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3f3f47;\n"
"}")
        self.btn_play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon)
        self.btn_play.setIconSize(QtCore.QSize(48, 48))
        self.btn_play.setObjectName("btn_play")
        self.btn_pause = QtWidgets.QPushButton(Dialog)
        self.btn_pause.setEnabled(True)
        self.btn_pause.setGeometry(QtCore.QRect(165, 130, 70, 70))
        self.btn_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pause.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border-radius: 35px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #28272c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3f3f47;\n"
"}")
        self.btn_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon1)
        self.btn_pause.setIconSize(QtCore.QSize(48, 48))
        self.btn_pause.setObjectName("btn_pause")
        self.btn_reset = QtWidgets.QPushButton(Dialog)
        self.btn_reset.setEnabled(True)
        self.btn_reset.setGeometry(QtCore.QRect(260, 140, 50, 50))
        self.btn_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reset.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #28272c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3f3f47;\n"
"}")
        self.btn_reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reset.setIcon(icon2)
        self.btn_reset.setIconSize(QtCore.QSize(30, 30))
        self.btn_reset.setObjectName("btn_reset")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Stay Focus"))
        self.label.setText(_translate("Dialog", "00:00:00"))
import files_rc
